package com.opticalix.storage.bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "NOTE".
 */
public class Note {

    private Long id;
    private String content;
    private java.util.Date create_date;
    private java.util.Date update_date;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Note() {
    }

    public Note(Long id) {
        this.id = id;
    }

    public Note(Long id, String content, java.util.Date create_date, java.util.Date update_date) {
        this.id = id;
        this.content = content;
        this.create_date = create_date;
        this.update_date = update_date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public java.util.Date getCreate_date() {
        return create_date;
    }

    public void setCreate_date(java.util.Date create_date) {
        this.create_date = create_date;
    }

    public java.util.Date getUpdate_date() {
        return update_date;
    }

    public void setUpdate_date(java.util.Date update_date) {
        this.update_date = update_date;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
